### ISSUE TITLE
Mock enum types

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/openapi-nodegen-mockers#5]
eg:

```yaml
in: query
name: sortBy
type: string
required: false
enum:
  - name
  - from
  - to
  - id
```

mock should generate a string which is one of the possible values
